CREATE DATABASE PkSchool;
USE PkSchool;

CREATE TABLE Courses(
Course_Id INT PRIMARY KEY IDENTITY(1,1),
Title VARCHAR(50) NOT NULL,
Stream VARCHAR(50) NOT NULL,
Type VARCHAR(50) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL);

CREATE TABLE Assignments(
Assignment_Id INT PRIMARY KEY IDENTITY(1,1),
Title VARCHAR(50) NOT NULL,
Description VARCHAR(150) NOT NULL,
SubDate DATE NOT NULL,
OralMark INT NOT NULL,
TotalMark INT NOT NULL);

CREATE TABLE Students(
Student_Id INT PRIMARY KEY IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
DateOfBirth DATE NOT NULL,
TuitionFees INT NOT NULL);

CREATE TABLE Trainers(
Trainer_Id INT PRIMARY KEY IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Subject VARCHAR(50) NOT NULL);

CREATE TABLE AssignmentCourse(
Course_Id INT,
Assignment_Id INT,
PRIMARY KEY(Course_Id,Assignment_Id),
FOREIGN KEY (Course_id) REFERENCES Courses (Course_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Assignment_id) REFERENCES Assignments (Assignment_id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE StudentCourse(
Course_Id INT,
Student_Id INT,
PRIMARY KEY(Course_Id,Student_Id),
FOREIGN KEY (Course_id) REFERENCES Courses (Course_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Student_id) REFERENCES Students (Student_id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE TrainerCourse(
Course_Id INT,
Trainer_Id INT,
PRIMARY KEY(Course_Id,Trainer_Id),
FOREIGN KEY (Course_id) REFERENCES Courses (Course_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Trainer_id) REFERENCES Trainers (Trainer_id) ON DELETE CASCADE ON UPDATE CASCADE);
        